version: '3.3'
services:
  db:
    build: ./db
    restart: always
    container_name: findawayMySQL
    environment:
      MYSQL_DATABASE: 'findaway'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'userpass'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  api:
    build: .
    restart: always
    container_name: findawayAPI
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    expose:
      - '3000'

# Names our volume
volumes:
  db_data: 
