version: '3.3'
services:
  db:
    build: ./db
    restart: always
    container_name: $db_url
    environment:
      MYSQL_DATABASE: $database
      MYSQL_ROOT_PASSWORD: $root_pwd
      MYSQL_USER: $db_user
      MYSQL_PASSWORD: $db_user_pwd
    ports:
      - $db_ports
    expose:
      - $db_port
    env_file:
      - .env

  api:
    build: .
    restart: always
    container_name: findawayAPI
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    ports:
      - $ports
    expose:
      - $port

# Names our volume
volumes:
  db_data: 
